# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-14 19:27
from __future__ import unicode_literals

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=156)),
            ],
            options={
                'verbose_name_plural': 'Cameras',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='GetFeaturedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.common.models.get_uploaded_file_path)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Get Featured Requests',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('instagram_handle', models.CharField(blank=True, help_text='Maximum 30 characters, including the @', max_length=31, null=True)),
                ('location', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Requesters',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='getfeaturedrequest',
            name='requester_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Requester'),
        ),
        migrations.AddField(
            model_name='camera',
            name='get_featured_request_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.GetFeaturedRequest'),
        ),
    ]
