# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-01-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_getfeaturedrequest_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='getfeaturedrequest',
            name='audio',
            field=models.URLField(blank=True, help_text='URL to the hosted media (AWS, Soundcloud, etc.)', null=True),
        ),
    ]
