# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-05 22:16
from __future__ import unicode_literals

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_getfeaturedrequest_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('participant_social', models.CharField(help_text='Maximum 30 characters, including the @', max_length=31)),
                ('description', models.TextField()),
                ('quote', models.CharField(max_length=128)),
                ('player_title_display', models.CharField(max_length=64)),
                ('player_subtitle_display', models.CharField(max_length=64)),
                ('audio', models.FileField(help_text='URL to the hosted media (AWS, Soundcloud, etc.)', storage=storages.backends.s3boto3.S3Boto3Storage(bucket='aovfileupload-dev'), upload_to=apps.common.models.get_podcast_file_path)),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archive_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Image to be displayed below to the player on the webpage.', upload_to=apps.common.models.get_uploaded_file_path)),
                ('display_type', models.CharField(choices=[('EI', 'Episode Image'), ('BI', 'Background Image'), ('RI', 'Related Image'), ('PI', 'Player Image')], max_length=2)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
