# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-27 18:02
from __future__ import unicode_literals

import apps.common.models
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'states', app_label='discover')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0019_auto_20181102_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=128)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name_plural': 'Downloaders',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(upload_to=apps.common.models.get_uploaded_file_path)),
                ('name', models.CharField(max_length=64)),
                ('social_handle', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Photographers',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('social_handle', models.CharField(max_length=64)),
                ('website', models.URLField()),
                ('downloadable_file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='aovfileupload-dev'), upload_to=apps.common.models.get_uploaded_file_path)),
                ('profile_image', models.ImageField(upload_to=apps.common.models.get_uploaded_file_path)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.common.models.get_uploaded_file_path)),
                ('fun_fact_1', models.CharField(blank=True, max_length=256, null=True)),
                ('fun_fact_2', models.CharField(blank=True, max_length=256, null=True)),
                ('fun_fact_3', models.CharField(blank=True, max_length=256, null=True)),
                ('fun_fact_4', models.CharField(blank=True, max_length=256, null=True)),
                ('fun_fact_5', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='StatePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.State')),
            ],
            options={
                'verbose_name_plural': 'State Photographers',
            },
        ),
        migrations.CreateModel(
            name='StatePhotographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('feature_start', models.DateTimeField()),
                ('feature_end', models.DateTimeField()),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.Photographer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.State')),
            ],
            options={
                'verbose_name_plural': 'State Photographers',
            },
        ),
        migrations.CreateModel(
            name='StateSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sponsorship_start', models.DateTimeField()),
                ('sponsorship_end', models.DateTimeField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.Sponsor')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.State')),
            ],
            options={
                'verbose_name_plural': 'State Sponsors',
            },
        ),
        migrations.AddField(
            model_name='downloader',
            name='state_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.StateSponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='statesponsor',
            unique_together=set([('sponsor', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='statephotographer',
            unique_together=set([('photographer', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='statephoto',
            unique_together=set([('photo', 'state')]),
        ),
        migrations.RunPython(load_fixture),
    ]
