# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_user_signup_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceUser',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Marketplace Users',
                'proxy': True,
            },
            bases=('account.user',),
        ),
    ]
