# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('photo_click', 'Photo Click'), ('photo_flag', 'Photo Flag'), ('photo_imp', 'Photo Impression')], max_length=32),
        ),
    ]
