# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
