# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinterest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='interest_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('star', 'Star')], max_length=10),
        ),
    ]
