# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='userinterest',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
