# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20161222_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('account.user',),
        ),
    ]
