# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_gear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('item_make', 'item_model'), 'verbose_name_plural': 'gear'},
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='make',
            new_name='item_make',
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='model',
            new_name='item_model',
        ),
    ]
