# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_db_search_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('account.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest_type',
            field=models.CharField(choices=[('like', 'Like'), ('star', 'Star')], max_length=10),
        ),
    ]
