# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170224_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowedUser',
        ),
        migrations.AddField(
            model_name='user',
            name='social_url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
