# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 23:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
