# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20170625_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(blank=True, choices=[('ST', 'Standard'), ('MK', 'Marketplace')], default='ST', max_length=3, null=True),
        ),
    ]
