# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_source',
            field=models.CharField(blank=True, choices=[('ST', 'Standard'), ('MK', 'Marketplace'), ('WS', 'Website')], default='ST', max_length=3, null=True),
        ),
    ]
