# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('push_notifications', '0002_auto_20160106_0850'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('action', models.CharField(choices=[('A', 'AoV Pick'), ('C', 'Comment'), ('F', 'Follower'), ('U', 'Upvote')], max_length=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notifications.APNSDevice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
