# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-07 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_pushnotificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationrecord',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushnotificationrecord',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
