# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-22 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180307_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationrecord',
            options={'verbose_name_plural': 'Notification Records'},
        ),
    ]
