# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180307_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='action',
            field=models.CharField(choices=[('A', 'AoV Pick'), ('C', 'Comment'), ('F', 'Follower'), ('T', 'Tagged'), ('U', 'Upvote')], max_length=1),
        ),
    ]
