# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-09 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20180319_1118'),
        ('communication', '0004_auto_20180322_0938'),
    ]

    operations = [
    ]
