# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0003_auto_20170313_1314'),
        ('communication', '0005_merge_20180408_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationrecord',
            name='fcm_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
        ),
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.APNSDevice'),
        ),
    ]
