# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20180726_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='action',
            field=models.CharField(choices=[('A', 'AoV Pick'), ('C', 'Comment'), ('F', 'Follower'), ('R', 'Feedback Reply'), ('T', 'Tagged'), ('U', 'Upvote')], max_length=1),
        ),
    ]
