# Generated by Django 2.0.13 on 2019-06-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_directmessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='fcm_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcm_django.FCMDevice'),
        ),
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='push_notifications.APNSDevice'),
        ),
        migrations.AlterField(
            model_name='pushnotificationrecord',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
