# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-12 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('display_date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='QuoteSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Quote Subscribers',
            },
        ),
    ]
