# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:09
from __future__ import unicode_literals

import apps.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=apps.common.models.get_uploaded_file_path)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_data', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(choices=[('category', 'Category'), ('tag', 'Tag')], default='tag', max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(related_name='category', to='photo.PhotoClassification'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_feed',
            field=models.ManyToManyField(to='photo.PhotoFeed'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='photo.PhotoClassification'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
