# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_category_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
