# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 03:21
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'categories', app_label='photo')
    call_command('loaddata', 'photo_feeds', app_label='photo')

class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20170605_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoclassification',
            name='admin_order_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(load_fixture),
    ]
