# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20161222_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photofeed',
            options={'default_permissions': ('add', 'change', 'delete', 'manage', 'view')},
        ),
    ]
