# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-17 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'categories', app_label='photo')
    call_command('loaddata', 'photo_feeds', app_label='photo')

class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photoclassification_admin_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoclassification',
            name='photo_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo.PhotoFeed'),
        ),
        migrations.RunPython(load_fixture),
    ]
