# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20161224_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFeedPhoto',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'feed photos',
                'verbose_name': 'feed photo',
            },
            bases=('photo.photo',),
        ),
        migrations.CreateModel(
            name='StarredPhoto',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('photo.photo',),
        ),
        migrations.AlterModelOptions(
            name='photofeed',
            options={'default_permissions': ('add', 'change', 'delete', 'manage', 'view'), 'verbose_name': 'feed', 'verbose_name_plural': 'feeds'},
        ),
    ]
