# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
