# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_photo_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedPhoto',
            fields=[
            ],
            options={
                'verbose_name': 'flagged photo',
                'proxy': True,
                'verbose_name_plural': 'flagged photos',
            },
            bases=('photo.photo',),
        ),
        migrations.AddField(
            model_name='photofeed',
            name='photo_limit',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True, verbose_name='max photos to display'),
        ),
        migrations.AddField(
            model_name='photofeed',
            name='randomize',
            field=models.BooleanField(default=False),
        ),
    ]
