# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-16 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_photovote'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aov_feed_add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
