# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-28 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_photo_aov_feed_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoclassification',
            name='admin_order_value',
        ),
    ]
