# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-09 14:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_photocomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='mentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
