# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-25 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_photocomment_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_data',
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_aperture',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_camera_settings',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_iso',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_lens',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_shutter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_time_of_day',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
