# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_auto_20180525_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
