# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_photo_photo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='bts_camera_make',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_camera_model',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='bts_photo_editor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
