# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-13 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0019_auto_20181102_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment', to='photo.Photo'),
        ),
    ]
