# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-14 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0020_auto_20190313_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
