# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0021_auto_20190314_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovote',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_vote', to='photo.Photo'),
        ),
    ]
